# Generated by Django 2.2.10 on 2021-11-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ansver',
            new_name='answer',
        ),
    ]
