# Generated by Django 2.2.10 on 2021-11-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211115_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_ansver',
            new_name='user_answer',
        ),
    ]
